server:
  port: 8014
spring:
  application:
      name: microservice-consumer-movie-feign-configuration-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.kvlt.cloud.feign.UserFeignClient: DEBUG
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000 # 加长hystrix超时时间
#hystrix.command.default.execution.timeout.enabled: false # 禁用超时时间
#feign.hystrix.enabled: false # 禁用hystrix


