server:
  port: 7901
spring:
  application:
      name: microservice-provider-user
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicDinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.kvlt: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true