server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidsky11/config-server-repo
          #username:    # 仓库用户
          #password:    # 密码



