server:
  port: 8079
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidsky11/config-server-repo
          username:
          password:
encrypt:
  key: foo



