server:
  port: 7900
spring:
  application:
      name: microservice-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    paltform: h2
    #schema: classpath:schema.sql
    #data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicDinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.kvlt: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true