server:
  port: 8012
spring:
  application:
      name: microservice-consumer-movie-ribbon-withour-eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: false
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7901