server:
  port: 8081
spring:
  application:
    name: microservice-eureka-client

eureka:
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
      prefer-ip-address: true