server:
  port: 8013
spring:
  application:
      name: microservice-consumer-movie-feign
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true