server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidsky11/config-server-repo
          search-paths:  # 搜索路径
            - foo   # foo路径
            - bar   # bar路径

security:
  basic:
    enabled: true
  user:
    name: user
    password: password123



