server:
  port: 8022
spring:
  application:
      name: microservice-hystrix-turbine
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
turbine:
  aggregator:
    clusterConfig: default
    #clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX
  appConfig: microservice-consumer-movie-ribbon-with-hystrix,microservice-provider-user
  cluster-name-expression: "'default'"   # 正则表达式

logging:
  level:
    root: info
    com.netflix.turbine.monitor: DEBUG